[package]
name = "llcc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
colored = "*"
strum = { version = "*", features = ["derive"] }
uuid = { version = "*", features = ["v4"] }
num = "*"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
