[package]
name = "llcc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
colored = "*"
uuid = { version = "*", features = ["v4"] }

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
